# Generated by Django 6.0.5 on 2026-05-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="názov"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="ďalšie informácie"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="", verbose_name="logo"),
                ),
            ],
            options={
                "verbose_name": "poskytovateľ",
                "verbose_name_plural": "poskytovatelia",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrojstenCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=32, unique=True, verbose_name="kód"
                    ),
                ),
                (
                    "original_amount",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="pôvodná hodnota"
                    ),
                ),
                (
                    "remaining_amount",
                    models.PositiveIntegerField(verbose_name="zostávajúca hodnota"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="dátum vytvorenia"
                    ),
                ),
                ("expires_at", models.DateField(verbose_name="dátum expirácie")),
                ("note", models.TextField(blank=True, verbose_name="poznámka")),
            ],
            options={
                "verbose_name": "Trojsten poukážka",
                "verbose_name_plural": "Trojsten poukážky",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExternalCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, verbose_name="kód")),
                ("amount", models.PositiveIntegerField(verbose_name="hodnota")),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dátum vymenenia"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="dátum vytvorenia"
                    ),
                ),
                ("expires_at", models.DateField(verbose_name="dátum expirácie")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.provider",
                        verbose_name="poskytovateľ",
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app.trojstencoupon",
                        verbose_name="vymenené",
                    ),
                ),
            ],
            options={
                "verbose_name": "poukážka od poskytovateľa",
                "verbose_name_plural": "poukážky od poskytovateľa",
                "ordering": ["-claimed_by", "-expires_at", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("code"),
                        models.F("provider"),
                        name="externalcoupon__code__provider__unique",
                    )
                ],
            },
        ),
    ]
