# Generated by Django 6.0.5 on 2026-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trojstencoupon',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
