# Generated by Django 6.0.5 on 2026-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="coupon_alert_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ak je poukážok tohto poskytovateľa menej ako toto číslo, pošle sa upozornenie na email administrátora. Ak je prázdne, upozornenie sa neposiela.",
                null=True,
                verbose_name="upozorniť, ak je menej ako",
            ),
        ),
    ]
