# Generated by Django 6.0.5 on 2026-05-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_trojstencoupon_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externalcoupon",
            options={
                "ordering": ["-claimed_by", "-expires_at", "code"],
                "verbose_name": "poukážka od poskytovateľa",
                "verbose_name_plural": "poukážky od poskytovateľa",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "ordering": ["name"],
                "verbose_name": "poskytovateľ",
                "verbose_name_plural": "poskytovatelia",
            },
        ),
        migrations.AlterModelOptions(
            name="trojstencoupon",
            options={
                "ordering": ["code"],
                "verbose_name": "Trojsten poukážka",
                "verbose_name_plural": "Trojsten poukážky",
            },
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="hodnota"),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="dátum vymenenia"
            ),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="app.trojstencoupon",
                verbose_name="vymenené",
            ),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="code",
            field=models.CharField(max_length=64, verbose_name="kód"),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="dátum vytvorenia"
            ),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="expires_at",
            field=models.DateField(verbose_name="dátum expirácie"),
        ),
        migrations.AlterField(
            model_name="externalcoupon",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="app.provider",
                verbose_name="poskytovateľ",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="description",
            field=models.TextField(blank=True, verbose_name="ďalšie informácie"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="logo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="logo"),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="názov"),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="code",
            field=models.CharField(
                editable=False, max_length=32, unique=True, verbose_name="kód"
            ),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="dátum vytvorenia"
            ),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="expires_at",
            field=models.DateField(verbose_name="dátum expirácie"),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="note",
            field=models.TextField(blank=True, verbose_name="poznámka"),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="original_amount",
            field=models.PositiveIntegerField(
                editable=False, verbose_name="pôvodná hodnota"
            ),
        ),
        migrations.AlterField(
            model_name="trojstencoupon",
            name="remaining_amount",
            field=models.PositiveIntegerField(verbose_name="zostávajúca hodnota"),
        ),
    ]
